// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gncyibvbejqrlvzkpdnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduY3lpYnZiZWpxcmx2emtwZG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODI5NTIsImV4cCI6MjA3MjQ1ODk1Mn0.miFkWmf-tppK6929g5Fu0CQAw7FvGNMihk8QNCNrhgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});